name: pytest
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 install pytest

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first
